# Generated by Django 3.2.3 on 2021-06-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('score', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('small_image_url', models.URLField()),
                ('kcal_100g', models.FloatField(default=0, null=True)),
                ('sugar_100g', models.FloatField(default=0, null=True)),
                ('salt_100g', models.FloatField(default=0, null=True)),
                ('fat_100g', models.FloatField(default=0, null=True)),
                ('categories', models.ManyToManyField(to='database.Category')),
            ],
        ),
    ]
